# -*- coding: utf-8 -*-
"""temel_egitim_ogrenci_yonetim_sistemi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuughXR_qdnLjIzupyD-H5CtgIys_lT_

# **Temel Veri Tipleri**

Python da temelde 4 farklı veri tipi vardır



*   Integer - tam sayı veri tipi - int() 85 90 -78 0
*   Float - ondalıklı sayı veri tipidir - float() 1.94 0.0 -87.96
*   Boolean - mantıksal veri tipi - bool() True False.
*  String - alfanümerik, karakter dizi  - str() 'merhaba' "merhaba" '''merhaba''' '''merhaba'''

not : ekrana çıktı vermek yani yazdırmak için `print()` komutunu kullanırız
"""

print(15)
print(85.96)
print(True)
print("Nehir")

"""not: yorum satırı oluşturmak için `#` kullanılır"""

# öğrenci ile ilgili temel veri tiplerini yazdıran uygulama
print(15) #öğrencinin yaşı yazdırıldı
print(85.96) #öğrencinin ortalaması float veri olarak yazdırıldı
print(True) #öğrencinin okula deva durumu boolean veri olarak yazdırıldı
print("Nehir") #öğrencinin adı string veri olarak yazdırıldı
#yukarıda bir öğrenciye ait temel veri tipleri kullanılarak çeşitli bilgiler yazdırıldı

"""`type()` methodu verinin tipini verir"""

print(type(8))
print(type(5.4))
print(type(False))
print(type('Nehir'))

"""Değişken kendisine değer atanan kavramdır"""

yas = 14
print(yas)
ortalama = 85.6
print(ortalama)
durum = True
print(durum)
ad = "Nehir"
print(ad)

print(type(ad))